# Generated by Django 6.0 on 2026-02-16 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='article',
            field=models.CharField(default='N/A', max_length=50, unique=True, verbose_name='Артикул'),
        ),
    ]
