# Generated by Django 6.0 on 2026-02-16 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0002_product_article'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='article',
            field=models.CharField(blank=True, default='N/A', max_length=50, null=True, unique=True, verbose_name='Артикул'),
        ),
    ]
